dist: precise
language: node_js
node_js:
  - node

cache:
  directories:
    - node_modules
jobs:
  fast_finish: true
  before_install:
    - "npm config set spin false"
    - "npm install -g npm"
    - "npm install -g ionic"
    - cd ./ionic/
  install: 
    - npm install
  script:
    - ionic serve
